# Generated by Django 2.0.13 on 2022-08-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('index', models.TextField()),
                ('file', models.FileField(upload_to='')),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
